# Generated by Django 6.0.1 on 2026-02-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartDetails', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'addtocart',
            },
        ),
    ]
